name: Logging

inputs:

  color:
    required: true
    type: string

  message:
    required: true
    type: string

runs:
  using: "composite"
  steps:

    # -------------------------------- Linux ---------------------------------
    
    - name: "Include scripts"
      shell: bash
      run: |
        echo ${{ github.action_path }} >> $GITHUB_PATH
        ls ${{ github.action_path }}/../
        source ${{ github.action_path }}/../other-folder/script-foo.sh

    - name: ""
      shell: bash
      run: |
        pecho "Hello actions" "RED"
